export const ADD_CHAT = "ADD_CHAT";

export const UPDATE_CHAT = "UPDATE_CHAT";

export const BLOCK_CHAT = "BLOCK_CHAT";

export const ERASE_CHAT = "ERASE_CHAT";

export const DELETE_CHAT = "DELETE_CHAT";

export const SEND_MESSAGE = "SEND_MESSAGE";

export const UPDATE_MESSAGE = "UPDATE_MESSAGE";

export const DELETE_MESSAGE = "DELETE_MESSAGE";

export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";

export const REPLY_TO_MESSAGE = "REPLY_TO_MESSAGE";

export const UPDATE_REPLY_TO_MESSAGE = "UPDATE_REPLY_TO_MESSAGE";

export const DELETE_REPLY_TO_MESSAGE = "DELETE_REPLY_TO_MESSAGE";
